baseURL = "https://nickpalenchar.com/"
languageCode = "en-us"
title = "Nick Palenchar ğŸ‘¨â€ğŸ’»"
theme = "hugo-flex"
sectionPagesMenu = "main"
publishDir = "docs"

rss = "To subscribe to this RSS feed, copy its address and paste it into your favorite feed reader."
[params]
description = "Thoughts on programming and the Tech Industry (and maybe other ramblings)"
avatar = "/profile.png" # path to profile image
color = "#7a4e8d"


[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[[menu.nav]]
name = "Posts"
url = "posts/"
weight = 1

[[menu.nav]]
name = "Tags"
url = "tags/"
weight = 2


[[params.social]]
  name = "github"
  url = "https://github.com/nickpalenchar"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/nickpalenchar"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/palencharizard"


[permalinks]
  posts = "/:filename"

